export type StoredBot = {
  id: string;
  name: string;
  description: string;
  source: "AI" | "Upload";
  market: string;
  createdAt: string;
  xml: string;
};


export function buildBotXml(opts: {
  name: string;
  description: string;
  market?: string;
  stake?: number;
  martingale?: number;
  takeProfit?: number;
  stopLoss?: number;
}) {
  const {
    name,
    description,
    market = "R_100",
    stake = 0.35,
    martingale = 2,
    takeProfit = 25,
    stopLoss = 500,
  } = opts;
  const esc = (s: string) =>
    s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

  return `<?xml version="1.0" encoding="UTF-8"?>
<xml xmlns="https://developers.google.com/blockly/xml" is_dbot="true" collection="false">
  <!-- Generated by Tronix Forge -->
  <!-- Bot: ${esc(name)} -->
  <!-- Strategy: ${esc(description)} -->
  <variables>
    <variable id="stake">stake</variable>
    <variable id="martingale">martingale</variable>
    <variable id="takeProfit">takeProfit</variable>
    <variable id="stopLoss">stopLoss</variable>
  </variables>
  <block type="trade_definition" id="trade_definition" x="0" y="0">
    <statement name="TRADE_OPTIONS">
      <block type="trade_definition_market">
        <field name="MARKET_LIST">synthetic_index</field>
        <field name="SUBMARKET_LIST">random_index</field>
        <field name="SYMBOL_LIST">${esc(market)}</field>
      </block>
    </statement>
    <statement name="INITIALIZATION">
      <block type="variables_set">
        <field name="VAR" id="stake">stake</field>
        <value name="VALUE"><block type="math_number"><field name="NUM">${stake}</field></block></value>
        <next>
          <block type="variables_set">
            <field name="VAR" id="martingale">martingale</field>
            <value name="VALUE"><block type="math_number"><field name="NUM">${martingale}</field></block></value>
            <next>
              <block type="variables_set">
                <field name="VAR" id="takeProfit">takeProfit</field>
                <value name="VALUE"><block type="math_number"><field name="NUM">${takeProfit}</field></block></value>
                <next>
                  <block type="variables_set">
                    <field name="VAR" id="stopLoss">stopLoss</field>
                    <value name="VALUE"><block type="math_number"><field name="NUM">${stopLoss}</field></block></value>
                  </block>
                </next>
              </block>
            </next>
          </block>
        </next>
      </block>
    </statement>
  </block>
  <block type="after_purchase" id="after_purchase" x="0" y="400">
    <statement name="AFTERPURCHASE_STACK">
      <block type="controls_if">
        <value name="IF0"><block type="contract_check_result"><field name="CHECK_RESULT">win</field></block></value>
        <statement name="DO0">
          <block type="variables_set">
            <field name="VAR" id="stake">stake</field>
            <value name="VALUE"><block type="math_number"><field name="NUM">${stake}</field></block></value>
          </block>
        </statement>
      </block>
    </statement>
  </block>
</xml>
`;
}

export function downloadText(filename: string, content: string, type = "text/plain") {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

export function slugify(s: string) {
  return s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") || "bot";
}

export function downloadBotXml(bot: Pick<StoredBot, "name" | "xml">) {
  downloadText(`${slugify(bot.name)}.xml`, bot.xml, "application/xml");
}
