import JSZip from "jszip";
import { slugify } from "@/lib/botStore";
import { googleFontHref, type SiteBrand } from "@/lib/siteBrand";

/**
 * Every generated site is the same Tronix Forge trading app.
 * Only the brand name, logo, colours and fonts are swapped; the app itself is untouched.
 */
export const TEMPLATE_URL = "/bot-app-template.zip";

let templateCache: ArrayBuffer | null = null;

async function loadTemplate(): Promise<ArrayBuffer> {
  if (templateCache) return templateCache;
  const res = await fetch(TEMPLATE_URL);
  if (!res.ok) throw new Error("Could not download the site template");
  templateCache = await res.arrayBuffer();
  return templateCache;
}

function dataUrlToBase64(dataUrl: string) {
  const idx = dataUrl.indexOf(",");
  return idx === -1 ? dataUrl : dataUrl.slice(idx + 1);
}

/** Builds the branded site as a zip blob, ready to download or hand to hosting. */
export async function buildSiteZip(brand: SiteBrand, domain?: string): Promise<Blob> {
  const zip = await JSZip.loadAsync(await loadTemplate());

  const name = brand.name.trim() || "My Trading Hub";
  const tagline = brand.tagline.trim() || "Automated Deriv trading bots, ready to run.";
  const host = (domain || `${slugify(name)}.tronixforge.site`).replace(/^https?:\/\//, "");
  const logoExt = brand.logoFileName?.toLowerCase().endsWith(".svg") ? "svg" : "png";
  const logoPath = `/logo.${logoExt}`;

  // 1. brand.config.json: the template's white-label switchboard
  const configFile = zip.file("brand.config.json");
  if (configFile) {
    const config = JSON.parse(await configFile.async("string"));
    config.brand_name = name;
    config.brand_domain = host;
    config.domain_name = host;
    config.brand_hostname = { staging: `staging.${host}/dashboard`, production: `${host}/dashboard` };
    config.colors = {
      ...config.colors,
      primary: brand.primaryColor,
      secondary: brand.secondaryColor,
      tertiary: brand.primaryColor,
    };
    config.typography = {
      ...config.typography,
      font_family: { ...config.typography?.font_family, primary: brand.font },
    };
    config.platform = {
      ...config.platform,
      name,
      logo_path: logoPath,
      hostname: {
        production: { com: `bot.${host}` },
        staging: { com: `staging-bot.${host}` },
      },
    };
    zip.file("brand.config.json", JSON.stringify(config, null, 4));
  }

  // 2. index.html: title, meta, favicon and webfont
  const htmlFile = zip.file("index.html");
  if (htmlFile) {
    let html = await htmlFile.async("string");
    html = html
      .replace(/<title>[\s\S]*?<\/title>/, `<title>${name} - Automated Trading Bots</title>`)
      .replace(/(<meta name="title" content=")[^"]*(")/, `$1${name}$2`)
      .replace(/(<meta name="description" content=")[^"]*(")/, `$1${tagline}$2`)
      .replace(/(<meta property="og:title" content=")[^"]*(")/, `$1${name}$2`)
      .replace(/(<meta property="og:description" content=")[^"]*(")/, `$1${tagline}$2`)
      .replace(
        /<link rel="icon"[^>]*>/,
        `<link rel="icon" href="<%= assetPrefix %>${logoPath}" />`,
      )
      .replace(
        "</head>",
        `    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="stylesheet" href="${googleFontHref(brand.font)}" />
        <style>
            :root {
                --brand-primary: ${brand.primaryColor};
                --brand-secondary: ${brand.secondaryColor};
                --brand-font: "${brand.font}", system-ui, sans-serif;
            }
            body,
            .body {
                font-family: var(--brand-font);
            }
        </style>
    </head>`,
      );
    zip.file("index.html", html);
  }

  // 3. logo
  if (brand.logoDataUrl) {
    zip.file(`public/logo.${logoExt}`, dataUrlToBase64(brand.logoDataUrl), { base64: true });
  }

  // 4. handover notes
  zip.file(
    "BRANDING.md",
    `# ${name}\n\nGenerated by Tronix Forge. This is the standard Tronix trading app; only branding differs.\n\n- Name: ${name}\n- Tagline: ${tagline}\n- Domain: ${host}\n- Primary colour: ${brand.primaryColor}\n- Secondary colour: ${brand.secondaryColor}\n- Font: ${brand.font}\n- Logo: public${logoPath}\n\n## Run locally\n\n\`\`\`bash\nnpm install\nnpm start\n\`\`\`\n\n## Build for hosting\n\n\`\`\`bash\nnpm run build\n\`\`\`\n\nAll branding lives in \`brand.config.json\`; app logic is intentionally unchanged.\n`,
  );

  return zip.generateAsync({ type: "blob" });
}

export async function downloadSiteCode(brand: SiteBrand, domain?: string) {
  const blob = await buildSiteZip(brand, domain);
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `${slugify(brand.name || "tronix-site")}-site.zip`;
  a.click();
  URL.revokeObjectURL(url);
}
