import { createFileRoute, Link } from "@tanstack/react-router";
import { DollarSign } from "lucide-react";
import { AppShell, PageHeader } from "@/components/AppShell";

export const Route = createFileRoute("/_authenticated/commissions")({
  head: () => ({
    meta: [
      { title: "Commission Tracking — Tronix Forge" },
      {
        name: "description",
        content: "Monitor payable commissions generated by trading activity across your Tronix Forge sites.",
      },
      { property: "og:title", content: "Commission Tracking — Tronix Forge" },
      { property: "og:description", content: "Monitor your earnings and payable commissions." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: CommissionsPage,
});

function CommissionsPage() {
  return (
    <AppShell>
      <PageHeader
        icon={DollarSign}
        title="Commission Tracking"
        subtitle="Monitor your earnings and payable commissions"
      />
      <div className="grid place-items-center rounded-3xl border border-dashed border-border bg-card/50 p-16 text-center">
        <div>
          <div className="mx-auto grid size-20 place-items-center rounded-3xl bg-accent">
            <DollarSign className="size-9 text-primary" />
          </div>
          <h2 className="mt-6 text-2xl font-bold">No sites found</h2>
          <p className="mt-2 text-muted-foreground">Create a site first to start tracking commissions.</p>
          <Link to="/" className="mt-6 inline-flex font-semibold text-primary hover:underline">
            Create your first site
          </Link>
        </div>
      </div>
    </AppShell>
  );
}
