/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAiGeneratorRouteImport } from './routes/_authenticated/ai-generator'
import { Route as AuthenticatedAiSignalsRouteImport } from './routes/_authenticated/ai-signals'
import { Route as AuthenticatedAnnouncementsRouteImport } from './routes/_authenticated/announcements'
import { Route as AuthenticatedBotStoreRouteImport } from './routes/_authenticated/bot-store'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedDeploymentsRouteImport } from './routes/_authenticated/deployments'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedEarningsRouteImport } from './routes/_authenticated/earnings'
import { Route as AuthenticatedLiveTradingRouteImport } from './routes/_authenticated/live-trading'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTutorialsRouteImport } from './routes/_authenticated/tutorials'
import { Route as AuthenticatedUpdatesRouteImport } from './routes/_authenticated/updates'
import { Route as AuthenticatedWebsiteEditorRouteImport } from './routes/_authenticated/website-editor'
import { Route as AuthenticatedXmlBotsRouteImport } from './routes/_authenticated/xml-bots'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminApiKeysRouteImport } from './routes/_authenticated/admin/api-keys'
import { Route as AuthenticatedAdminBotsRouteImport } from './routes/_authenticated/admin/bots'
import { Route as AuthenticatedAdminDerivRouteImport } from './routes/_authenticated/admin/deriv'
import { Route as AuthenticatedAdminDomainsRouteImport } from './routes/_authenticated/admin/domains'
import { Route as AuthenticatedAdminHostingRouteImport } from './routes/_authenticated/admin/hosting'
import { Route as AuthenticatedAdminPackagesRouteImport } from './routes/_authenticated/admin/packages'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiGeneratorRoute =
  AuthenticatedAiGeneratorRouteImport.update({
    id: '/ai-generator',
    path: '/ai-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSignalsRoute = AuthenticatedAiSignalsRouteImport.update({
  id: '/ai-signals',
  path: '/ai-signals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnnouncementsRoute =
  AuthenticatedAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBotStoreRoute = AuthenticatedBotStoreRouteImport.update({
  id: '/bot-store',
  path: '/bot-store',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDeploymentsRoute =
  AuthenticatedDeploymentsRouteImport.update({
    id: '/deployments',
    path: '/deployments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEarningsRoute = AuthenticatedEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLiveTradingRoute =
  AuthenticatedLiveTradingRouteImport.update({
    id: '/live-trading',
    path: '/live-trading',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTutorialsRoute = AuthenticatedTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUpdatesRoute = AuthenticatedUpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWebsiteEditorRoute =
  AuthenticatedWebsiteEditorRouteImport.update({
    id: '/website-editor',
    path: '/website-editor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedXmlBotsRoute = AuthenticatedXmlBotsRouteImport.update({
  id: '/xml-bots',
  path: '/xml-bots',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminApiKeysRoute =
  AuthenticatedAdminApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminBotsRoute = AuthenticatedAdminBotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDerivRoute = AuthenticatedAdminDerivRouteImport.update({
  id: '/deriv',
  path: '/deriv',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminDomainsRoute =
  AuthenticatedAdminDomainsRouteImport.update({
    id: '/domains',
    path: '/domains',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminHostingRoute =
  AuthenticatedAdminHostingRouteImport.update({
    id: '/hosting',
    path: '/hosting',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPackagesRoute =
  AuthenticatedAdminPackagesRouteImport.update({
    id: '/packages',
    path: '/packages',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/ai-generator': typeof AuthenticatedAiGeneratorRoute
  '/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/bot-store': typeof AuthenticatedBotStoreRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/live-trading': typeof AuthenticatedLiveTradingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/website-editor': typeof AuthenticatedWebsiteEditorRoute
  '/xml-bots': typeof AuthenticatedXmlBotsRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/bots': typeof AuthenticatedAdminBotsRoute
  '/admin/deriv': typeof AuthenticatedAdminDerivRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/hosting': typeof AuthenticatedAdminHostingRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/ai-generator': typeof AuthenticatedAiGeneratorRoute
  '/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/announcements': typeof AuthenticatedAnnouncementsRoute
  '/bot-store': typeof AuthenticatedBotStoreRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/deployments': typeof AuthenticatedDeploymentsRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/earnings': typeof AuthenticatedEarningsRoute
  '/live-trading': typeof AuthenticatedLiveTradingRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/updates': typeof AuthenticatedUpdatesRoute
  '/website-editor': typeof AuthenticatedWebsiteEditorRoute
  '/xml-bots': typeof AuthenticatedXmlBotsRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/admin/bots': typeof AuthenticatedAdminBotsRoute
  '/admin/deriv': typeof AuthenticatedAdminDerivRoute
  '/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/admin/hosting': typeof AuthenticatedAdminHostingRoute
  '/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/ai-generator': typeof AuthenticatedAiGeneratorRoute
  '/_authenticated/ai-signals': typeof AuthenticatedAiSignalsRoute
  '/_authenticated/announcements': typeof AuthenticatedAnnouncementsRoute
  '/_authenticated/bot-store': typeof AuthenticatedBotStoreRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/deployments': typeof AuthenticatedDeploymentsRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/earnings': typeof AuthenticatedEarningsRoute
  '/_authenticated/live-trading': typeof AuthenticatedLiveTradingRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tutorials': typeof AuthenticatedTutorialsRoute
  '/_authenticated/updates': typeof AuthenticatedUpdatesRoute
  '/_authenticated/website-editor': typeof AuthenticatedWebsiteEditorRoute
  '/_authenticated/xml-bots': typeof AuthenticatedXmlBotsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/api-keys': typeof AuthenticatedAdminApiKeysRoute
  '/_authenticated/admin/bots': typeof AuthenticatedAdminBotsRoute
  '/_authenticated/admin/deriv': typeof AuthenticatedAdminDerivRoute
  '/_authenticated/admin/domains': typeof AuthenticatedAdminDomainsRoute
  '/_authenticated/admin/hosting': typeof AuthenticatedAdminHostingRoute
  '/_authenticated/admin/packages': typeof AuthenticatedAdminPackagesRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/ai-generator'
    | '/ai-signals'
    | '/announcements'
    | '/bot-store'
    | '/commissions'
    | '/deployments'
    | '/domains'
    | '/earnings'
    | '/live-trading'
    | '/settings'
    | '/support'
    | '/tutorials'
    | '/updates'
    | '/website-editor'
    | '/xml-bots'
    | '/admin/api-keys'
    | '/admin/bots'
    | '/admin/deriv'
    | '/admin/domains'
    | '/admin/hosting'
    | '/admin/packages'
    | '/admin/support'
    | '/admin/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/ai-generator'
    | '/ai-signals'
    | '/announcements'
    | '/bot-store'
    | '/commissions'
    | '/deployments'
    | '/domains'
    | '/earnings'
    | '/live-trading'
    | '/settings'
    | '/support'
    | '/tutorials'
    | '/updates'
    | '/website-editor'
    | '/xml-bots'
    | '/'
    | '/admin/api-keys'
    | '/admin/bots'
    | '/admin/deriv'
    | '/admin/domains'
    | '/admin/hosting'
    | '/admin/packages'
    | '/admin/support'
    | '/admin/users'
    | '/admin'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/ai-generator'
    | '/_authenticated/ai-signals'
    | '/_authenticated/announcements'
    | '/_authenticated/bot-store'
    | '/_authenticated/commissions'
    | '/_authenticated/deployments'
    | '/_authenticated/domains'
    | '/_authenticated/earnings'
    | '/_authenticated/live-trading'
    | '/_authenticated/settings'
    | '/_authenticated/support'
    | '/_authenticated/tutorials'
    | '/_authenticated/updates'
    | '/_authenticated/website-editor'
    | '/_authenticated/xml-bots'
    | '/_authenticated/'
    | '/_authenticated/admin/api-keys'
    | '/_authenticated/admin/bots'
    | '/_authenticated/admin/deriv'
    | '/_authenticated/admin/domains'
    | '/_authenticated/admin/hosting'
    | '/_authenticated/admin/packages'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-generator': {
      id: '/_authenticated/ai-generator'
      path: '/ai-generator'
      fullPath: '/ai-generator'
      preLoaderRoute: typeof AuthenticatedAiGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-signals': {
      id: '/_authenticated/ai-signals'
      path: '/ai-signals'
      fullPath: '/ai-signals'
      preLoaderRoute: typeof AuthenticatedAiSignalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/announcements': {
      id: '/_authenticated/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AuthenticatedAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bot-store': {
      id: '/_authenticated/bot-store'
      path: '/bot-store'
      fullPath: '/bot-store'
      preLoaderRoute: typeof AuthenticatedBotStoreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deployments': {
      id: '/_authenticated/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof AuthenticatedDeploymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/earnings': {
      id: '/_authenticated/earnings'
      path: '/earnings'
      fullPath: '/earnings'
      preLoaderRoute: typeof AuthenticatedEarningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/live-trading': {
      id: '/_authenticated/live-trading'
      path: '/live-trading'
      fullPath: '/live-trading'
      preLoaderRoute: typeof AuthenticatedLiveTradingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tutorials': {
      id: '/_authenticated/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof AuthenticatedTutorialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/updates': {
      id: '/_authenticated/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof AuthenticatedUpdatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website-editor': {
      id: '/_authenticated/website-editor'
      path: '/website-editor'
      fullPath: '/website-editor'
      preLoaderRoute: typeof AuthenticatedWebsiteEditorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/xml-bots': {
      id: '/_authenticated/xml-bots'
      path: '/xml-bots'
      fullPath: '/xml-bots'
      preLoaderRoute: typeof AuthenticatedXmlBotsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/api-keys': {
      id: '/_authenticated/admin/api-keys'
      path: '/api-keys'
      fullPath: '/admin/api-keys'
      preLoaderRoute: typeof AuthenticatedAdminApiKeysRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/bots': {
      id: '/_authenticated/admin/bots'
      path: '/bots'
      fullPath: '/admin/bots'
      preLoaderRoute: typeof AuthenticatedAdminBotsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/deriv': {
      id: '/_authenticated/admin/deriv'
      path: '/deriv'
      fullPath: '/admin/deriv'
      preLoaderRoute: typeof AuthenticatedAdminDerivRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/domains': {
      id: '/_authenticated/admin/domains'
      path: '/domains'
      fullPath: '/admin/domains'
      preLoaderRoute: typeof AuthenticatedAdminDomainsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/hosting': {
      id: '/_authenticated/admin/hosting'
      path: '/hosting'
      fullPath: '/admin/hosting'
      preLoaderRoute: typeof AuthenticatedAdminHostingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/packages': {
      id: '/_authenticated/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AuthenticatedAdminPackagesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminApiKeysRoute: typeof AuthenticatedAdminApiKeysRoute
  AuthenticatedAdminBotsRoute: typeof AuthenticatedAdminBotsRoute
  AuthenticatedAdminDerivRoute: typeof AuthenticatedAdminDerivRoute
  AuthenticatedAdminDomainsRoute: typeof AuthenticatedAdminDomainsRoute
  AuthenticatedAdminHostingRoute: typeof AuthenticatedAdminHostingRoute
  AuthenticatedAdminPackagesRoute: typeof AuthenticatedAdminPackagesRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminApiKeysRoute: AuthenticatedAdminApiKeysRoute,
    AuthenticatedAdminBotsRoute: AuthenticatedAdminBotsRoute,
    AuthenticatedAdminDerivRoute: AuthenticatedAdminDerivRoute,
    AuthenticatedAdminDomainsRoute: AuthenticatedAdminDomainsRoute,
    AuthenticatedAdminHostingRoute: AuthenticatedAdminHostingRoute,
    AuthenticatedAdminPackagesRoute: AuthenticatedAdminPackagesRoute,
    AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedAiGeneratorRoute: typeof AuthenticatedAiGeneratorRoute
  AuthenticatedAiSignalsRoute: typeof AuthenticatedAiSignalsRoute
  AuthenticatedAnnouncementsRoute: typeof AuthenticatedAnnouncementsRoute
  AuthenticatedBotStoreRoute: typeof AuthenticatedBotStoreRoute
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedDeploymentsRoute: typeof AuthenticatedDeploymentsRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedEarningsRoute: typeof AuthenticatedEarningsRoute
  AuthenticatedLiveTradingRoute: typeof AuthenticatedLiveTradingRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTutorialsRoute: typeof AuthenticatedTutorialsRoute
  AuthenticatedUpdatesRoute: typeof AuthenticatedUpdatesRoute
  AuthenticatedWebsiteEditorRoute: typeof AuthenticatedWebsiteEditorRoute
  AuthenticatedXmlBotsRoute: typeof AuthenticatedXmlBotsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedAiGeneratorRoute: AuthenticatedAiGeneratorRoute,
  AuthenticatedAiSignalsRoute: AuthenticatedAiSignalsRoute,
  AuthenticatedAnnouncementsRoute: AuthenticatedAnnouncementsRoute,
  AuthenticatedBotStoreRoute: AuthenticatedBotStoreRoute,
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedDeploymentsRoute: AuthenticatedDeploymentsRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedEarningsRoute: AuthenticatedEarningsRoute,
  AuthenticatedLiveTradingRoute: AuthenticatedLiveTradingRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTutorialsRoute: AuthenticatedTutorialsRoute,
  AuthenticatedUpdatesRoute: AuthenticatedUpdatesRoute,
  AuthenticatedWebsiteEditorRoute: AuthenticatedWebsiteEditorRoute,
  AuthenticatedXmlBotsRoute: AuthenticatedXmlBotsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
